version: "3"
services:
 redis:
  image: redis:alpine
  ports:
    - "6377:6379"
  volumes:
    - redis_data:/data
  networks:
    - app-network
  hostname: redis
 kazan_reds_bot:
   build:
     context: .
     dockerfile: Dockerfile
   image: kzn_reds_app
   container_name: kazan_reds_bot
   env_file: .env
   environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
   expose:
     - 8200  
   networks:
    - app-network
   restart: always
   command: python /app/main.py

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
